# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erik Can
email: yeserikcan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the portfolio of Erik Karwatowski, a full-stack developer. Thank you for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erikcan.com.local" # the base hostname & protocol for your site
twitter_username: erikkarwatowski
github_username:  erikleon

# Build settings
markdown: kramdown
source: src
destination: public
exclude: ['node_modules']
